## Basic data types
Python has a number of basic types including integers, floats, booleans, and strings. These data types behave in ways that are familiar from other programming languages.
python --version 3.6.0

### Numbers

In [9]:
x = 3
print(x, type(x))
print(x + 1)
print(x - 1)
print(x * 2)  # Multiplication
print(x ** 2) # Exponentiation

3 <class 'int'>
4
2
6
9
4


In [10]:
x += 1
print(x)
x *= 2
print(x)

5
10


In [16]:
y = 2.5
print(type(y))
print(y, y + 1, y*2, y**2)

<class 'float'>
2.5 3.5 5.0 6.25


### Booleans
Python uses english words (and, or, not)

t = True
f = False
print(type(t))
print(t and f)
print(t or f)
print(not t)
print(t != f)    # Logical XOR; prints "True"

### Strings

In [24]:
hello = "hello" # String literals can use double or
world = 'world' # single quotes; it doesn't matter.
print(hello)
print(len(hello)) # String length
hw = hello + " " +  world + "!" # String concatenation
print(hw)
hw12 = '%s %s %d' % (hello, world, 12) # sprintf style string formatting
print(hw12)

hello
5
hello world!
hello world 12


In [27]:
# String objects have a bunch of useful methods; for example:
s = "hello"
print(s.capitalize())  # Capitalize a string
print(s.upper())   # Convert a string to uppercase
print(s.rjust(7))  # Right-justify a string, padding with spaces
print(s.center(7)) # Center a string, padding with spaces
print(s.replace('l','ell'))  # Replaces all instances of one substring
                             # with another
print('    world'.strip())  # Strip leading and trailing whitespace

Hello
HELLO
  hello
 hello 
heellello
world


## Containers
Python includes several built-in container types: lists, dictionaries, sets, and tuples.

### Lists
A list is the Python equivalent of an array, but is resizeable and can contain elements of different types:

In [34]:
xs = [3, 1, 2]   # Create a list
print(xs, xs[2]) # Prints "[3, 1, 2] 2"
print(xs[-1])    # Negative indices count from the end of the list
xs[2] = "foo"    # Lists can contain elements of different types
print(xs)
xs.append('bar')  #Add a new element to the end of the list
print(xs)
x = xs.pop()      # Remove and return the last element of the list
print(x, xs)

[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']


### Slicing
In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing:

In [55]:
nums = range(5) #Range is a built-in function that creates a list 
                #of integers
print(nums, list(nums), type(nums))
print(nums[2:4], list(nums[2:4]))
print(nums[2:], list(nums[2:]))
print(nums[:2], list(nums[:2])) #slice from start to index 2 (exclusive)
print(nums[:], list(nums[:]))
print(nums[:-1], list(nums[:-1]))
lnums = list(nums)
lnums[2:4] = [8, 9]  # Assign a new sublist to a slice
print(lnums)

range(0, 5) [0, 1, 2, 3, 4] <class 'range'>
range(2, 4) [2, 3]
range(2, 5) [2, 3, 4]
range(0, 2) [0, 1]
range(0, 5) [0, 1, 2, 3, 4]
range(0, 4) [0, 1, 2, 3]
[0, 1, 8, 9, 4]


### Loops
You can loop over the elements of a list like this:

In [56]:
animals = ['cat', 'dog', 'bird']
for animal in animals:
    print(animal)

cat
dog
bird


In [57]:
# to access to the index of each element use enumerate function
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))

#1: cat
#2: dog
#3: bird


### List comprehensions
Consider the following code that computes square numbers:

In [58]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)

[0, 1, 4, 9, 16]


In [59]:
# It is possible to make the last code simpler using list comprehension
squares = [x ** 2 for x in nums]
print(squares)

[0, 1, 4, 9, 16]


In [61]:
# List comprehensions can also contain conditions
evenSquares = [x ** 2 for x in nums if x % 2 == 0]
print(evenSquares)

[0, 4, 16]


### Dictionaries
A dictionary stores (key, value) pairs, similar to a Map in Java or an object in Javascript. You can use it like this:

In [72]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a dictionary
print(d['cat'], d, type(d))
print('cat' in d)  # Check if a dictionary has a given key
d['fish'] = 'wet'  # Set an entry in a dictionary
print(d['fish'])
print(d.get('monkey', 'N/A')) # Get an element with a default;
print(d.get('fish', 'N/A')) # Get an element with a default;
print(d)
del d['fish']  # Remove an element form a dictionary
print(d.get('fish', 'N/A'))

cute {'cat': 'cute', 'dog': 'furry'} <class 'dict'>
True
wet
N/A
wet
{'cat': 'cute', 'dog': 'furry', 'fish': 'wet'}
N/A


### Loops
Iterate over the keys in a dictionary its easy

In [1]:
d = {'person': 2, 'cat': 4, 'spider':8}
for animal in d:
    legs = d[animal]
    print('A %s has %d legs' % (animal, legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


In [3]:
#If you want access to keys and their corresponding values, 
#use the iteritems method:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
    print('A %s has %d legs' % (animal, legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


### Dictionary comprehensions
These are similar to list comprehensions, but allow you to easily construct dictionaries. For example:

In [5]:
nums = [0, 1, 2, 3, 4]
evenNumToSquare = {x: x ** 2 for x in nums if x % 2 == 0}
print(evenNumToSquare)

{0: 0, 2: 4, 4: 16}


### Sets
A set is an unordered collection of distinct elements. As a simple example, consider the following

In [12]:
animals = {'cat', 'dog'}
print('cat' in animals)
print('fish' in animals)
animals.add('fish')
print('fish' in animals)
print(animals, 'len %d' % len(animals))
animals.add('cat')
print(len(animals))
animals.remove('cat')
print(len(animals))

True
False
True
{'fish', 'cat', 'dog'} len 3
3
2


### loops in set
Iterating over a set has the same syntax as iterating over a list; however since sets are unordered, you cannot make assumptions about the order in which you visit the elements of the set:

In [13]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))

#1: fish
#2: cat
#3: dog


In [15]:
# Set comprehensions
from math import sqrt
nums = {int(sqrt(x)) for x in range(30)}
print(nums)

{0, 1, 2, 3, 4, 5}


### Tuples
A tuple is an (immutable) ordered list of values

In [17]:
d = {(x, x + 1): x for x in range(10)} #dictionary with tuple keys
print(d)
t = (5, 6)    # Create a tuple
print(type(t))
print(d[t])
print(d[(1, 2)])

{(0, 1): 0, (1, 2): 1, (2, 3): 2, (3, 4): 3, (4, 5): 4, (5, 6): 5, (6, 7): 6, (7, 8): 7, (8, 9): 8, (9, 10): 9}
<class 'tuple'>
5
1


## Functions
Python functions are defined using the def keyword. For example:

In [18]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))

negative
zero
positive


In [20]:
#functions will be often defined to take optional keyword arguments, 
#like this:
def hello(name, loud=False):
    if loud:
        print('HELLO, %s!' % name.upper())
    else:
        print('Hello, %s' % name)
    
hello('Bob')
hello('Fred', loud=True)

Hello, Bob
HELLO, FRED!


## Classes
The syntax for defining classes in Python is straightforward:


In [21]:
class Greeter(object):
    
    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable
        
    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)

            
g = Greeter('Fred')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method
g.greet(loud=True)   # Call an instance method with an addit param

Hello, Fred
HELLO, FRED!


# Numpy
Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays

## Arrays
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integer. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

In [27]:
import numpy as np

a = np.array([1, 2, 3])    # Create a rank 1 array
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5                   # Change an element of the array
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [31]:
b = np.array([[1,2,3],[4,5,6]])  # Create a rank 2 array
print(b.shape)
print(b)
print(b[0,0], b[0,1], b[1,0])

(2, 3)
[[1 2 3]
 [4 5 6]]
1 2 4


In [33]:
# Numpy also provides many functions to create arrays:
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)

b = np.ones((1,2))    # Create an array of all ones
print(b)

c = np.full((2,2), 7) # Create a constant array
print(c)

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)

e = np.random.random((2,2)) # Create an array filled with random values
print(e)

[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]]
[[7 7]
 [7 7]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 0.90967705  0.71109866]
 [ 0.08395721  0.83350506]]


## Array indexing
Numpy offers several ways to index into arrays

### Slicing
Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [35]:
import numpy as np

# Create a rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2
b = a[:2,1:3]
print(b)

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])
b[0, 0] = 77   # b[0, 0] is the same piece of data as a[0, 1]
print(a)
print(a[0, 1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
77


In [37]:
#You can also mix integer indexing with slice indexing.
import numpy as np

# Create a rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
rowR1 = a[1,:]    # Rank 1 view of the second row of a 
rowR2 = a[1:2,:]  # Rank 2 view of the second row of a 

print(rowR1, rowR1.shape)
print(rowR2, rowR2.shape)

# We can make the same distinction when accessing columns of an array
colR1 = a[:, 1]
colR2 = a[:, 1:2]
print(colR1, colR1.shape)
print(colR2, colR2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


### Integer array indexing
When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [43]:
import numpy as np

a = np.array([[1,2],[3,4],[5,6]])

print(a, a[[0,1,2],[0,1,0]])
print(np.array([a[0,0], a[1,1], a[2,0]]))

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

[[1 2]
 [3 4]
 [5 6]] [1 4 5]
[1 4 5]
[2 2]
[2 2]


In [48]:
# One useful trick with integer array indexing is selecting or 
# mutating one element from each row of a matrix:
import numpy as np

# Create an array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

print(a)

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])
print(np.arange(4))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[0 1 2 3]
